# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = 2
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "node1" do |node1_config|
    node1_config.vm.network "public_network",
      use_dhcp_assigned_default_route: true
    node1_config.vm.provider :virtualbox do |vb|
      vb.customize [
        'modifyvm', :id, 
        '--natdnshostresolver1', 'on', 
        '--memory', '2048', 
        '--cpus', '2']
    end
  end

  config.vm.define "node2" do |node2_config|
    node2_config.vm.network "public_network",
      use_dhcp_assigned_default_route: true
    node2_config.vm.provider :virtualbox do |vb|
      vb.customize [
        'modifyvm', :id, 
        '--natdnshostresolver1', 'on', 
        '--memory', '2048', 
        '--cpus', '2']
    end
  end

  config.vm.define "node3" do |node3_config|
    node3_config.vm.network "public_network",
      use_dhcp_assigned_default_route: true
    node3_config.vm.provider :virtualbox do |vb|
      vb.customize [
        'modifyvm', :id, 
        '--natdnshostresolver1', 'on', 
        '--memory', '2048', 
        '--cpus', '2']
    end
  end

end